import Head from "next/head";
import Script from "next/script";
import Link from "next/link";

const Header = () => {
    return (
        <>
            <Head>
                <title>IMC - Índice de Massa Corporal</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />        
            </Head>
            
            <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" />
            <header className="container">
                <nav className="navbar navbar-expand-lg bg-body-tertiary">
                    <div className="container-fluid">
                        <Link className="navbar-brand" href="/">Kba</Link>
                        <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                            <span className="navbar-toggler-icon"></span>
                        </button>
                        <div className="collapse navbar-collapse" id="navbarNav">
                        <ul className="navbar-nav">
                            <li className="nav-item">
                                <Link className="nav-link" href="/">Home</Link>
                            </li>
                            <li className="nav-item">
                                <Link className="nav-link" href="/sobre">Sobre</Link>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link" target="_blank" href="https://www.linkedin.com/in/katarine-albuquerque/">Linkedin</a>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link" target="_blank" href="https://github.com/albuquerque-katarine?tab=repositories">GitHub</a>
                            </li>                        
                        </ul>
                        </div>
                    </div>
                </nav>
            </header>
        </>

    )
}
export default Header;